config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :users, only: [:index, :show, :edit, :update, :delete] do
    get :followings, on: :member
    get :followers, on: :member
  end

  resources :relationships, only: [:create, :destroy]

  #検索結果をpostsコントローラのsearchアクションへ送信
  get 'search' => 'posts#search'
  root to: 'posts#index'
  resources :posts, only: [:index, :new, :create, :show, :edit, :update] do
    resource :favorites, only: [:create, :destroy]
  end

  resources :tweets

  namespace :api, format: 'json' do
    namespace :v1 do
      resources :comments
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :post
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  has_many :favorites

  is_impressionable counter_cache: true

  def favorited_by?(user)
    favorites.where(user_id: user.id).exists?
  end

  # ソート用のインスタンスメソッド
  def self.sort(selection)
    case selection
    when 'new'
      all.order(created_at: :DESC)
    when 'old'
      all.order(created_at: :ASC)
    when 'likes'
      find(Favorite.group(:post_id).order(Arel.sql('count(post_id) desc')).pluck(:post_id))
    when 'dislikes'
      find(Favorite.group(:post_id).order(Arel.sql('count(post_id) asc')).pluck(:post_id))
    when 'pvmany'
      order('impressions_count desc').all
    when 'pvless'
      order('impressions_count asc').all
    end
  end

end

app/models/relationship.rb
class Relationship < ApplicationRecord
  belongs_to :user
  belongs_to :follow, class_name: "User"

  validates :user_id, presence: true
  validates :follow_id, presence: true
end

app/models/tweet.rb
class Tweet < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :favorites
  has_many :favorite_posts, through: :favorites, source: :post
  has_many :posts

  has_many :tweets

  #フォローしているユーザー達とのアソシエーション
  has_many :relationships
  has_many :followings, through: :relationships,
                        source: :follow

  #フォローされているユーザー達とのアソシエーション
  has_many :reverse_of_relationships, foreign_key: "follow_id",
                                      class_name: "Relationship"

  has_many :followers, through: :reverse_of_relationships, source: :user

  #取得したユーザーをフォローしている場合はtrueを返す
  def following?(other_user)
    self.followings.include?(other_user)
  end

  def follow(other_user)
    unless self == other_user
      self.relationships.find_or_create_by(follow_id: other_user.id)
    end
  end

  def unfollow(other_user)
    relationship = self.relationships.find_by(follow_id: other_user.id)
    relationship.destroy if relationship
  end
end

app/controllers/api/v1/comments_controller.rb
class Api::V1::CommentsController < ApplicationController

  def index
    @data = [
      { author: "Pete Hunt", text: "This is one comment" },
      { author: "Jordan Walke", text: "This is *another* comment"}
    ]
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    added_attrs = [:username, :email, :password_confirmation, :remember_me]
    devise_parameter_sanitizer.permit :sign_up, keys: added_attrs
    devise_parameter_sanitizer.permit :account_update, keys: added_attrs
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @post = Post.find(params[:post_id])
    favorite = current_user.favorites.build(post_id: params[:post_id])
    favorite.save
    redirect_to posts_path
  end

  def destroy
    @post = Post.find(params[:post_id])
    favorite = Favorite.find_by(post_id: params[:post_id], user_id: current_user.id)
    favorite.destroy
    redirect_to posts_path
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  before_action :authenticate_user!, except: [:index, :show]
  impressionist :actions => [:index, :search], :unique => [:impressionable_id, :ip_address]

  def new
    @post = Post.new
  end

  def create
    @post = current_user.posts.new(post_params)
    if @post.save
      redirect_to posts_path
    end
  end

  def index
    @posts = Post.order(created_at: :desc).page(params[:page])
  end

  def search
    selection = params[:keyword]
    @posts = Post.sort(selection)
  end

  def show
    @post = Post.find(params[:id])
    impressionist(@post, nil, :unique => [:impressionable_id, :ip_address])
  end

  def edit
  end

  private
  def post_params
    params.require(:post).permit(:title, :description, :content)
  end
end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

  before_action :set_user

  def create
    following = current_user.follow(@user)
    if following.save
      flash[:success] = "ユーザーをフォローしました"
      redirect_to @user
    else
      flash.now[:alert] = "ユーザーのフォローに失敗しました"
      redirect_to @user
    end
  end

  def destroy
    following = current_user.unfollow(@user)
    if following.destroy
      flash[:success] = "ユーザーのフォローを解除しました"
      redirect_to @user
    else
      flash.now[:alert] = "ユーザーのフォロー解除に失敗しました"
      redirect_to @user
    end
  end

  private
  def set_user
    @user = User.find(params[:relationship][:follow_id])
  end
end

app/controllers/tweets_controller.rb
class TweetsController < ApplicationController

  before_action :authenticate_user!, except: [:index]

  def new
    @tweet = Tweet.new
  end

  def create
    @tweet = current_user.tweets.new(tweet_params)
    @tweet.save
    redirect_to tweets_path
  end

  def index
    @tweet = Tweet.new
    @tweets = Tweet.all
  end

  def show
    @tweet = Tweet.find(params[:id])
  end

  private
    def tweet_params
      params.require(:tweet).permit(:body)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  include UsersHelper

  before_action :authenticate_user!
  # before_action :correct_user
  before_action :admin_user, only: :destroy
  before_action :set_user

  def index
    @users = User.all
  end

  def show
    @posts = @user.posts  #ユーザーの作品
    @favorite_posts = @user.favorite_posts  #ユーザーがお気に入りした作品
    @tweets = @user.tweets.order(created_at: :desc).page(params[:page]) #ユーザーのツイート
    @relationship = current_user.relationships.find_by(follow_id: @user.id)  #DBから相手ユーザーとのRelationshipを取得する
    @set_relationship = current_user.relationships.new  #ビューから参照するための、空のRelationshipモデルを作成する。
  end

  def edit
  end

  def destroy
    User.find(params[:id]).destroy
    redirect_to users_url
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def followings
    @users = @user.followings.page(params[:page])
  end

  def followers
    @users = @user.followers.page(params[:page])
  end

  private
  def user_params
    params.require(:user).permit(:username)
  end

  def set_user
    @user = User.find(params[:id])
  end

  def correct_user
    @user = User.find(params[:id])
    redirect_to root_url unless current_user?(@user)
    flash[:danger] = "無効なアドレスです"
  end

  def admin_user
    redirect_to root_url unless current_user.admin?
  end
end

app/helpers/api/v1/comments_helper.rb
module Api::V1::CommentsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/tweets_helper.rb
module TweetsHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # ログイン中のユーザーであれば真を返す
  def current_user?(user)
    user == current_user
  end

end

app/views/favorites/create.html.slim
h1 Favorites#create
p Find me in app/views/favorites/create.html.slim

app/views/favorites/destroy.html.slim
h1 Favorites#destroy
p Find me in app/views/favorites/destroy.html.slim

app/views/layouts/application.html.slim
doctype html
html
  head
    title
      | TagFunction
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application'
    / , 'data-turbolinks-track': 'reload'
  body

    ul
      li= link_to '投稿一覧', posts_path
      li= link_to '述べる', tweets_path
      - if user_signed_in?
        li= link_to 'マイページ', user_path(current_user)
        li.dropdown
          a.dropdown-toggle href="#" メニュー
          ul
            li= link_to '新規投稿', new_post_path
            li= link_to 'ユーザー一覧', users_path
            li= link_to 'ログアウト', destroy_user_session_path, method: :delete
      - else
        li= link_to '新規登録', new_user_registration_path
        li= link_to 'ログイン', new_user_session_path

    p.notice
      = notice
    p.alert
      = alert
    = yield

    br
    br
    br
    = debug(params) if Rails.env.development?

app/views/posts/_result.html.slim
p= paginate @posts

- @posts.each do |post|
  p
    = link_to post.user.email, user_path(post.user.id)
    br
    = link_to post.title, post_path(post.id)
    br
    = post.created_at
    br
    = "PV数: #{post.impressionist_count}"
    = "／"

    - if user_signed_in?
      - if post.favorited_by?(current_user)
        = link_to "いいね: #{post.favorites.count}", post_favorites_path(post.id), method: :delete
      - else
        = link_to "いいね: #{post.favorites.count}", post_favorites_path(post.id), method: :post
    - else
      = post.favorites.count

p= paginate @posts

app/views/posts/_select_form.html.slim
= form_with model: @post, url: search_path, method: :get, local: true do |form|
  = form.select :keyword, [ ['投稿が新しい順', 'new'],
                            ['投稿が古い順', 'old'],
                            ['いいねが多い順', 'likes'],
                            ['いいねが少ない順', 'dislikes'],
                            ['PVが多い順', 'pvmany'],
                            ['PVが少ない順', 'pvless'],
                          ]
  = form.submit

app/views/posts/edit.html.slim
h1
  | Posts#edit
p
  | Find me in app/views/posts/edit.html.erb

app/views/posts/index.html.slim
h1 投稿一覧

br
= render 'select_form'
br
= render 'result'

app/views/posts/new.html.slim
h2 新規投稿

= form_with model: @post, local: true do |f|
  p
    = f.label :title
    = f.text_field :title, placeholder: 'タイトル'
  p
    = f.label :description
    = f.text_area :description, placeholder: 'あらすじ'
  p
    = f.label :content
    = f.text_area :content, placeholder: '本文'
  = f.submit '投稿'

app/views/posts/search.html.slim
h1 検索結果

= render 'select_form'

= render 'result'

app/views/posts/show.html.slim
h1 作品のタイトルが入る

p= @post.title
p= @post.description
p= @post.content
p= "PV：#{@post.impressionist_count}"

- if @post.favorited_by?(current_user)
  p= link_to "いいね：#{@post.favorites.count}", post_favorites_path(@post.id), method: :delete
- else
  p= link_to "いいね：#{@post.favorites.count}", post_favorites_path(@post.id), method: :post

= react_component('CommentBox', url: 'api/v1/comments.json')

app/views/relationships/_follow_button.html.slim
- unless current_user == user
  - if current_user.following?(user)
    = form_with model: @relationship, url: relationship_path, method: :delete, local: true do |f|
      = f.hidden_field :follow_id, value: user.id
      = f.submit "フォロー中"
  -else
    = form_with model: @set_relationship, url: relationships_path, local: true do |f|
      = f.hidden_field :follow_id, value: user.id
      = f.submit "フォロー"

app/views/shared/_tweets.html.slim
hr
- @tweets.each do |tweet|
  = link_to tweet.user.username, user_path(tweet.user_id)
  br
  = link_to tweet.body, tweet_path(tweet.id)
  hr

app/views/tweets/index.html.slim
h1 述べる
= form_with model: @tweet, local: true do |f|
  p
    = f.text_area :body
  p= f.submit "述べる"

hr
- @tweets.each do |tweet|
  = link_to tweet.user.username, user_path(tweet.user_id)
  br
  = link_to tweet.body, tweet_path(tweet.id)
  hr

app/views/tweets/new.html.slim
h1 Tweets#new
p Find me in app/views/tweets/new.html.slim

= form_with model: @tweet do |f|
  p
    = f.label :body, "述べる"
    = f.text_area :body
  p= f.submit "述べる"

app/views/tweets/show.html.slim
h1 Tweets#show
p Find me in app/views/tweets/show.html.slim

span
  ul
    hr
    li
      = link_to @tweet.user.username, user_path(@tweet.user.id)
      br
      = @tweet.body
      hr
- if current_user != @tweet.user
  - if current_user.following?(@tweet.user)
    = link_to "フォロー解除", user_relationship_path(@tweet.user.id)
  - else
    = link_to "フォローする", user_relationships_path(@tweet.user.id)

app/views/users/edit.html.slim
div
  = form_with model: @user, local: true do |f|
    p
      = f.label :username
      = f.text_field :username

    p= f.submit

app/views/users/followers.html.slim
h2 フォロワーの皆さん

- @users.each do |user|
  hr
  = "username: "
  = link_to user.username, user_path(user.id)

app/views/users/followings.html.slim
h2 フォローしている方々

- @users.each do |user|
  hr
  = "username: "
  = link_to user.username, user_path(user.id)

app/views/users/index.html.slim
h1 Users#index
p Find me in app/views/users/index.html.slim

- @users.each do |user|
  = link_to user.email, user_path(user)
  br
  - if current_user.admin? && !current_user?(user)
  = link_to "削除", user, method: :delete, data: { confirm: "良いの？" }
  br
  br

app/views/users/show.html.slim
br
br
br
h1 ユーザーのプロフィール

p
  = "名前 : "
  = @user.username
  = render 'relationships/follow_button', user: @user

  br
  = link_to "フォロー: #{@user.followings.count}", followings_user_path(@user.id)
  = "／"
  = link_to "フォロワー: #{@user.followers.count}", followers_user_path(@user.id)

p= link_to "プロフィール編集", edit_user_path(current_user)

br
br
br
br
br

h3 ="いいねした投稿： #{@favorite_posts.count}"
- @favorite_posts.each do |f_post|
  ul
    li
      = "タイトル"
      = f_post.title
      br
      = "あらすじ"
      = f_post.description
      br
      = "内容"
      = f_post.content

h3 ="投稿作品： #{@posts.count}"
- @posts.each do |post|
  ul
    li
      = "タイトル: "

      = post.title
      br
      = "あらすじ: "

      = post.description
      br
      = "内容: "

      = post.content

h3 ="マイ述べる：#{@tweets.count}"
- if @user.tweets.any?
ul
  li
    = render 'shared/tweets'

= paginate @tweets